version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    restart: always
    depends_on:    
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
        - .env
    links:
      - db
    depends_on:
     - db
    command: tail -f /dev/null


  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow
      MYSQL_PASSWORD: root
    volumes:
      - .data/db:/var/lib/mysql

